### ISSUE TITLE
Parameter name

### ISSUE THREAD

**Issue by equiman** [Secbyte/dotnet-sonarscanner#5]
This parameter `Organisation` need to be fixed `Organization`

**Comment by equiman** [comment]
I have created a PR.

https://github.com/Secbyte/dotnet-sonarscanner/pull/7

**Comment by joshuaduffy** [comment]
Thank you for your PR. However, we are using the UK English spelling of organisation.

**Comment by equiman** [comment]
I didn't know that. Thanks!
